---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: Fetching a specific property of an ec2 instance
    become: true
    shell: curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document|jq ".{{ Property_Name }}"
    register: output
    when: Property_Name is defined

  - set_fact:
      response_message: "{{ output.stdout }}"
    when:
    - Property_Name is defined
    - output is success

  - name: Fetching all properties of an ec2 instance
    become: true
    shell: curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document
    register: outputs
    when: Property_Name is not defined


  - set_fact:
      response_message: "{{ outputs.stdout }}"
    when:
    - Property_Name is not defined
    - outputs is success


  - debug:
      var: response_message